### PR TITLE
chore(build): support download Windows artifacts

### PR DESCRIPTION
**Pull request by yuchanns**
follow https://github.com/yetone/avante.nvim/issues/418

cc @aarnphm

### CODE REVIEW

**Comment by yuchanns** [comment]
https://github.com/yetone/avante.nvim/issues/474#issuecomment-2326525542

> It is unreasonable for the installation script to depend on $GITHUB_TOKEN, I will fix this issue as soon as possible.

Draft due to depend on $GITHUB_TOKEN and waiting the release of artifacts

**Comment by yetone** [comment]
Relying on GITHUB_TOKEN is unreasonable. I am currently modifying this logic. After I finish updating build.sh, could you help synchronize the related logic?

**Comment by yuchanns** [comment]
Sure

**Comment by yuchanns** [comment]
@yetone Please compress the window tarball with zip, otherwise it requires 7z tool to unarchive the tarball.

**Comment by yetone** [comment]
But:
image
https://github.com/yetone/avante.nvim/actions/runs/10684221085/job/29614138285

**Comment by yuchanns** [comment]
@yetone You can use Compress-Archive, eg: `Compress-Archive -Path "C:\Documents\*.txt" -DestinationPath "C:\Archives\TextFiles.zip"`

**Review by aarnphm — APPROVED** [review]

**Comment by yuchanns** [comment]
Holding for #502. Needs testing.

**Comment by yuchanns** [comment]
I believe it is ready now.

**Pull request merged**
