### PR TITLE
feat(clipboard): support windows

### PR DESCRIPTION
**Pull request by yuchanns**
refer to https://github.com/yetone/avante.nvim/issues/218#issuecomment-2316030910

### CODE REVIEW

**Comment by yuchanns** [comment]
There is a problem with the relative paths of images not working in Windows. Will need some time to find out solution.

**Comment by aarnphm** [comment]
is there a relative path? I thought the path would be absolute in this case no?

**Comment by yuchanns** [comment]
> is there a relative path? I thought the path would be absolute in this case no?

I paste the image into the chat box and get a relative path. Is this an unexpected behavior?

**Comment by yuchanns** [comment]
The img-clip.nvim supports using the absolute path https://github.com/HakonHarnes/img-clip.nvim/issues/80#issuecomment-2309812863. Windows is working with `use_absolute_path=true`.

**Review by aarnphm — APPROVED** [review]

**Pull request merged**
