### PR TITLE
feat/fix: AvanteEdit should immediately switch into insert mode

### PR DESCRIPTION
**Pull request by frankroeder**
Dear Maintainers,

I suggest that `AvanteEdit` should immediately switch to insert mode, as users most often want to input a prompt.

### CODE REVIEW

**Comment by Trevato** [comment]
Auto-insert mode would be frustrating. If I enter the `AvanteEdit` window by mistake, I'd have to hit `<Esc>` before I could use my exit keybind. If I want to paste I have to `<Esc>` first. The idea is you enter the window, then take action. If the action you want to take is insert, then just press your insert bind.

**Comment by Trevato** [comment]
Sure bad example but do you not find yourself cycling windows? 

I find myself using the `AvanteEdit` window just like any other buffer. Sometimes I want to edit my prompt. Are you also going to decide where to put my cursor when I enter the buffer and there is content?  

The majority of cases for me is default nvim behavior.

**Comment by aarnphm** [comment]
I would argue that this breaks the cycling workflow (+1 from trev here)

**Comment by frankroeder** [comment]
I'm not sure if we're talking about the same thing. I'm referring to the command triggered by `<Leader>ae` that allows you to "edit a selected block." This command opens a small input prompt next to the selected code, where you can input a command to edit it.

screenshot 2024-09-11 at 10 02 16

By default, this input window is empty, and I have not encountered any instances where text is already present. I apologize for any potential confusion with `AvanteEdit`. At least the code of the PR is still doing the right thing.

**Comment by aarnphm** [comment]
This is AvanteEdit

**Comment by frankroeder** [comment]
Just to add: It would follow the behavior of `vim.ui.input` being an input prompt.

**Comment by Trevato** [comment]
Yeah I'm aware of both input methods. My opinion remains.

**Comment by georgeguimaraes** [comment]
I had asked this over on Discussions as well:
https://github.com/yetone/avante.nvim/discussions/549

**Comment by aarnphm** [comment]
I kinda prefer multiple steps over progressive disclosure https://github.com/yetone/avante.nvim/issues/445#issuecomment-2327311194

**Review by aarnphm — CHANGES_REQUESTED** [review]
ehh I'm fine with this through a behaviour option (opt-in)

**Comment by aarnphm** [comment]
Hmm, I will close this PR. My reasoning are stated above.

feel free to open this again if you decide to add on option for this.

**Pull request closed without merging**
