### PR TITLE
fix(sidebar): allow /clear to be run multiple times

### PR DESCRIPTION
**Pull request by ddillert**
**Issue**: Running `/clear` multiple times in the sidebar triggers the following warning message:

```bash
E5108: Error executing lua: ....local/share/nvim/lazy/plenary.nvim/lua/plenary/path.lua:737: ENOENT: no such file or directory: /home/dd/.local/state/nvim/avante/__home__dd__Desktop__curl.c.json
stack traceback:
  [C]: in function 'assert'
  ....local/share/nvim/lazy/plenary.nvim/lua/plenary/path.lua:737: in function 'write'
  ...t/.local/share/nvim/lazy/avante.nvim/lua/avante/path.lua:54: in function 'save'
  ...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:1111: in function 'callback'
  ...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:1231: in function 'handle_submit'
  ...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:1341: in function <...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:1331>
```

**Fix**: This implementation adds a check to see if the history is empty. If it is, the sidebar will simply close without performing any additional actions, thereby preventing the error.

### CODE REVIEW

**Comment by yetone** [comment]
LGTM

**Review by aarnphm — APPROVED** [review]

**Review by aarnphm — APPROVED** [review]

**Comment by jackschedel** [comment]
Hi, I'm on the latest version of avante and still getting this error. It happens after running `:Avante Clear`, then running an ask. The error occurs as soon as the completion stops:
```
Error executing vim.schedule lua callback: ....local/share/nvim/lazy/plenary.nvim/lua/plenary/path.lua:737: ENOENT: no such file or directory: /Users/jack/.local/state/nvim/avante/__Use
rs__jack__reps__small_programs__distributed_operating_systems__coordinated_permission_protoactor__main.go.json
stack traceback:
        [C]: in function 'assert'
        ....local/share/nvim/lazy/plenary.nvim/lua/plenary/path.lua:737: in function 'write'
        ...k/.local/share/nvim/lazy/avante.nvim/lua/avante/path.lua:54: in function 'save'
        ...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:1263: in function 'on_complete'
        ...re/nvim/lazy/avante.nvim/lua/avante/providers/openai.lua:88: in function 'parse_response'
        ...ck/.local/share/nvim/lazy/avante.nvim/lua/avante/llm.lua:114: in function 'parse_stream_data'
        ...ck/.local/share/nvim/lazy/avante.nvim/lua/avante/llm.lua:150: in function <...ck/.local/share/nvim/lazy/avante.nvim/lua/avante/llm.lua:137>
        ```

**Comment by ddillert** [comment]
Thanks for your comment, @jackschedel! I was able to reproduce the bug following your description. I'll look into it and keep you updated on the progress.

**Comment by jackschedel** [comment]
Oh, I had just deleted it because I thought it might've been due to a make error, but apparantly not! Here it is again haha:

Hi, I'm on the latest version of avante and still getting this error. It happens after running `:Avante Clear`, then running an ask. The error occurs as soon as the completion stops:
```
Error executing vim.schedule lua callback: ....local/share/nvim/lazy/plenary.nvim/lua/plenary/path.lua:737: ENOENT: no such file or directory: /Users/jack/.local/state/nvim/avante/__Use
rs__jack__reps__small_programs__distributed_operating_systems__coordinated_permission_protoactor__main.go.json
stack traceback:
        [C]: in function 'assert'
        ....local/share/nvim/lazy/plenary.nvim/lua/plenary/path.lua:737: in function 'write'
        ...k/.local/share/nvim/lazy/avante.nvim/lua/avante/path.lua:54: in function 'save'
        ...local/share/nvim/lazy/avante.nvim/lua/avante/sidebar.lua:1263: in function 'on_complete'
        ...re/nvim/lazy/avante.nvim/lua/avante/providers/openai.lua:88: in function 'parse_response'
        ...ck/.local/share/nvim/lazy/avante.nvim/lua/avante/llm.lua:114: in function 'parse_stream_data'
        ...ck/.local/share/nvim/lazy/avante.nvim/lua/avante/llm.lua:150: in function <...ck/.local/share/nvim/lazy/avante.nvim/lua/avante/llm.lua:137>
```

(avante version):
image

**Pull request merged**
