### PR TITLE
revert(cohere): revert to gpt-4o as tokenizer

### PR DESCRIPTION
**Pull request by maxbrunet**
Hello there! 👋 

Same as #506

FYI the tokenizer can be download from Cohere directly, it would avoid the user from configuring a HuggingFace account in addition to the Cohere API token: https://docs.cohere.com/v2/docs/tokens-and-tokenizers#downloading-a-tokenizer

Thank you for this wonderful project! ❤️

### CODE REVIEW

**Comment by aarnphm** [comment]
thanks for the PR. I will kindly close this afaik the tokenizers library in Rust from HF doesn't support this

I will think about this once I update with tool use, given that it will be closely related to tokenizers

**Comment by maxbrunet** [comment]
Hey @aarnphm, thank you for looking into this, I can remove the comment if you prefer, the source of the tokenizer is not the problem, it is simply broken at the moment like Gemini even with the `HF_TOKEN` environment variable (same issue as the Gemini PR closed: #499). So it'd be nice if that could be merged, so the default config for the `cohere` provider can work out of the box.

The source of the tokenizer is merely something to consider when fixing the root of the problem

**Comment by aarnphm** [comment]
I'm fixing this atm, just that for cohere gpt-4o tokenizer wasn't as good, hence the token_id from hg

**Comment by aarnphm** [comment]
hi there, #765 should address this.

though for most stuff going forward, if the model is gated it is probably best to also set HF_TOKEN, given that we are depending on hf/tokenizers

**Pull request closed without merging**
